### ISSUE TITLE
大佬为什么我执行他提示没这个命令

### ISSUE THREAD

**Issue by mdeche101644** [TheHonestDearmer1/FixObsImgDpy#1]
(D:\mdech\Documents\Pythonenvs\kyticket) D:\mdech\Documents\Obsidian\Linux>pip install FixObsImgDpy
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: FixObsImgDpy in c:\users\mdech\appdata\roaming\python\python311\site-packages (0.1.0)

(D:\mdech\Documents\Pythonenvs\kyticket) D:\mdech\Documents\Obsidian\Linux>FixObsImgDpy
'FixObsImgDpy' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by TheHonestDearmer1** [comment]
我在我的新电脑环境下重新安装都没有这个问题喔？你看一下你python环境有什么问题？可能是python环境没有配置对
(base) PS C:\Users\11011> pip install FixObsImgDpy
Collecting FixObsImgDpy
  Downloading FixObsImgDpy-0.1.0-py3-none-any.whl.metadata (899 bytes)
Downloading FixObsImgDpy-0.1.0-py3-none-any.whl (2.7 kB)
Installing collected packages: FixObsImgDpy
Successfully installed FixObsImgDpy-0.1.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(base) PS C:\Users\11011> FixObsImgDpy
开始修改当前目录以下的md文件
